services:
  postgres:
    image: postgres:17
    container_name: pd_postgresql
    restart: always
    command: -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGRST_AUTHENTICATOR_PASSWORD: $PGRST_AUTHENTICATOR_PASSWORD
    volumes:
      - ./containers/postgresql-17/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./containers/postgresql-17/data:/var/lib/postgresql/data
      - ./backups:/mnt/backups

  postgrest:
    image: postgrest/postgrest
    container_name: pd_postgrest
    restart: always
    ports:
      - "3030:3000"
    depends_on:
      - postgres
    environment:
      PGRST_DB_URI: $PGRST_DB_URI
      PGRST_DB_SCHEMAS: $PGRST_DB_SCHEMAS
      PGRST_DB_ANON_ROLE: $PGRST_DB_ANON_ROLE
      PGRST_JWT_SECRET: $PGRST_JWT_SECRET
      PGRST_LOG_LEVEL: $PGRST_LOG_LEVEL

  pg-hero:
    image: ankane/pghero
    container_name: pd_pghero
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: $PGHERO_DATABASE_URL
  
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8181:8080"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "2345:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: patrick@ppseafield.com
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
