services:
  postgres:
    image: postgres:17.5-bookworm
    container_name: pd_db
    restart: always
    command: -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

