GET http://localhost:3030/

POST http://localhost:3030/rpc/create_session
Content-Type: application/json

{
    "username_text": "ppseafield",
    "password_text": "Traffic123!"
}


GET http://localhost:3030/tasks?select=id,created_by,created_at,completed_at,archived_at,task_order,journaled_by,routine_from,title,subtasks(id,task_id,parent_subtask_id,created_by,routine_from,created_at,completed_at,archived_at,task_order,title)
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicGlsZWRyaXZlcl91c2VyIiwidXNlcl9pZCI6IjAxOTNlNmE4LWY2ZTYtNGI3YS0xZGY2LTU1OWRmYjZhNTdhMSIsInNlc3Npb25faWQiOiIwMTkzZTZiMC0xOTM4LTliMGUtNWU0NS1iODEwZGU3ZjM4NzkiLCJpYXQiOjE3MzQ3NDIxMjAsImV4cCI6MTczNTM0NjkyMH0.VnvoA86DDFgpnniAaHXPABPwOdHBbOPXxvGNoe_N-wg
Content-Type: application/json

GET http://localhost:3000/api/tasks
Cookie: session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicGlsZWRyaXZlcl91c2VyIiwidXNlcl9pZCI6IjAxOTNlNmE4LWY2ZTYtNGI3YS0xZGY2LTU1OWRmYjZhNTdhMSIsInNlc3Npb25faWQiOiIwMTkzZTZjMS0yZTU2LTY3YWUtM2EyYi0xYTc4MmZjMzRiNmUiLCJpYXQiOjE3MzQ3NDMyNDAsImV4cCI6MTczNTM0ODA0MH0.Y2j7DZJWpFGLCG_vz7khML0oyn45GzLE1XnZF795Jb0; _pg_hero_solo_session=bUFMVVhZK0toa203NjBBdzNCT09FSXpsMHg5cTdPZFpKbVA3TjZ4dWxSZE94QkdpVCtoaVVDUnA5ZlVmMkN0U3VoNmxYQjkxVENFUEQyNGJvWW52ZFNob3NDNnI1Z2dHYkRPTGhiMWhMOVlpVXFFOHhFbSt3aW55SUFnQ0VkTnRicHF0ZGFzTHk3c3ZYQ3Y0VXNXbzkrZlFIL08wdmxNVEx1QlljemVZN1hRUUUxZ0dteGsveDBUdE5RRlNjMWFILS04cDBoN09hK1FJbkpxMVFzcDlyUFN3PT0%3D--51cf31dd6fee32ee4cbd6ae7aa7f49145ee24562; ndashboard:panel-0=250; v-0-0=250; v-1-0=250; v-2-0=250; v-3-0=250; v-4-0=250; v-0-1=250; v-0-2=250


GET http://localhost:3030/tasks?select=id%2Ccreated_by%2Cjournaled_by%2Croutine_from%2Ccreated_at%2Ccompleted_at%2Carchived_at%2Ctask_order%2Ctitle%2Csubtasks%28id%2Ctask_id%2Cparent_subtask_id%2Ctask_sheet_item_id%2Ccreated_by%2Croutine_from%2Ccreated_at%2Ccompleted_at%2Carchived_at%2Ctask_order%2Ctitle%29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicGlsZWRyaXZlcl91c2VyIiwidXNlcl9pZCI6IjAxOTNlNmE4LWY2ZTYtNGI3YS0xZGY2LTU1OWRmYjZhNTdhMSIsInNlc3Npb25faWQiOiIwMTkzZTZiMC0xOTM4LTliMGUtNWU0NS1iODEwZGU3ZjM4NzkiLCJpYXQiOjE3MzQ3NDIxMjAsImV4cCI6MTczNTM0NjkyMH0.VnvoA86DDFgpnniAaHXPABPwOdHBbOPXxvGNoe_N-wg
Content-Type: application/json
